# Generated by Django 2.2.5 on 2019-09-28 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date_time', models.DateTimeField()),
                ('max_participants', models.PositiveIntegerField(blank=True)),
                ('min_participants', models.PositiveIntegerField(blank=True)),
                ('descriptions', models.TextField()),
                ('status', models.BooleanField()),
                ('organizer_name', models.CharField(max_length=200)),
                ('category', models.ManyToManyField(to='Events.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.IntegerField()),
                ('attendance', models.BooleanField()),
                ('feedback', models.TextField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.Event')),
            ],
        ),
    ]
