# Generated by Django 2.2.5 on 2019-09-28 07:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_event_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 28, 7, 37, 14, 248774, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
